# Generated by Django 3.2.3 on 2021-08-26 20:58

import clients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавление в базу'),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default='This description', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='client',
            name='phoned',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата последнего звонка'),
        ),
        migrations.AddField(
            model_name='client',
            name='spec_files',
            field=models.FileField(blank=True, null=True, upload_to=clients.models.Client.upload_path, verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=False, verbose_name='Организатор группы'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_salesmanager',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.salesmanager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.userprofile', verbose_name='Группа')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='client',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.userprofile', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.userprofile', verbose_name='Группа'),
        ),
    ]
